#!/bin/bash

# An array of options
declare -a options=(
" aliases     -  .config/aliasrc"
" bash        -  .bashrc"
" bprofile     -  .bash_profile"
" zprofile    -  .config/zsh/.zprofile"
" dmenu       -  dmscripts/dmenu-custom/apps"
" sxhkd       -  .config/sxhkd/sxhkdrc"
" picom       -  .config/picom.conf"
" qtile       -  .config/qtile/config.py"
" vim         -  .config/nvim/init.lua"
" xinit       -  .config/X11/xinitrc"
" zsh         -  .config/zsh/.zshrc"
" zenv        -  .config/zsh/.zshenv"
" config      -  dmscripts/edit_config"
)

# Piping the above array into dmenu
# We use "printf '%s\n'" to format the array one item to a line.
if [ -z "$1" ]; then
        choice=$(printf '%s\n' "${options[@]}" | $LAUNCHER -i -l 15 -p 'Exit? ')
elif [ -n "$1" ]; then
        arg="$(printf '%s' "$1" | cut -d'.' -f2)"  # eliminate '.' from the beginnig if used
        choice=$(printf '%s\n' "${options[@]}" | grep -i "^ $arg")
fi

# Get file path
choice=${choice##* }

[ -z "$choice" ] &&  exit
# cd "$(dirname $choice)" || exit

if [ -f "$HOME/$choice" ]; then
	$TERMINAL -e $EDITOR "$HOME/$choice" 2>/dev/null
else
	$TERMINAL -e $EDITOR "$HOME/$choice"* 2>/dev/null
fi
